apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: go-pulsar-elasticsearch
  labels:
    app: go-pulsar-elasticsearch
spec:
  serviceName: go-pulsar-elasticsearch
  selector:
    matchLabels:
      app: go-pulsar-elasticsearch
  replicas: 24
  template:
    metadata:
      labels:
        app: go-pulsar-elasticsearch
      annotations:
        prometheus.io/port: "8002"
        prometheus.io/scrape: "true"            
    spec:
      containers:
        - name: go-pulsar-elasticsearch
          image: go-pulsar-elasticsearch:0.0.1
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 2
              memory: 1Gi
            limits:
              cpu: 12
              memory: 8Gi
          readinessProbe:
            httpGet:
              path: /ready
              port: 8002
            initialDelaySeconds: 5
            periodSeconds: 30
          livenessProbe:
            httpGet:
              path: /health
              port: 8002
            initialDelaySeconds: 7
            periodSeconds: 10
          env:
          - name: ENV
            value: "prod"
          ports:
            - containerPort: 8002
---
apiVersion: v1
kind: Service
metadata:
  name: go-pulsar-elasticsearch-svc
spec:
  selector:
    app: go-pulsar-elasticsearch
  type: ClusterIP
  ports:
    - name: service
      targetPort: 8002
      port: 8002
    - name: metrics
      port: 8001
      protocol: TCP
      targetPort: 8001